"""update database

Revision ID: ce539ae506b5
Revises: 
Create Date: 2024-08-24 21:47:02.238493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce539ae506b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flavour', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('date_created')
        batch_op.drop_column('flavor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flavor', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DATETIME(), nullable=True))
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('quantity')
        batch_op.drop_column('flavour')

    # ### end Alembic commands ###
